import React from "react";
import "./third.scss";



export default function Third() {
	return <div class="page">
    <div className="mainPage">
      <p>
      Lorem ipsum dolor sit, amet consectetur adipisicing elit. Earum dolores nulla hic perferendis animi fuga illo corrupti? Qui odio laborum, odit porro ducimus repellendus tempore repudiandae blanditiis delectus assumenda, perferendis nam, iusto dicta cupiditate praesentium illum quas aspernatur. Porro, molestias. Reiciendis officiis repellendus eos ullam asperiores, quod labore soluta iusto. Reiciendis doloremque rerum mollitia amet eos nisi magnam aut cupiditate a consectetur et libero, sint itaque asperiores voluptates possimus autem sunt fugit ad? Hic, commodi. Recusandae libero iusto quasi accusamus veniam? Delectus magnam ratione ab sed commodi vero atque, similique vel ipsam eveniet eius, exercitationem rerum temporibus quis repellat fugiat totam laboriosam nostrum illum sit. Perspiciatis, placeat reiciendis. Possimus illum in itaque placeat. Reiciendis sunt obcaecati voluptatibus! Suscipit sit ipsa sequi. Similique dolores esse ratione tempora eaque, iure voluptas iusto, eligendi deserunt aliquid expedita. Eum reiciendis officiis distinctio minima. Optio earum tempore sed labore placeat eius ratione recusandae sit consectetur. Blanditiis tempore debitis aspernatur voluptas natus dolorum! Incidunt error labore, dolore, at nihil earum voluptates suscipit praesentium rem nulla eveniet libero provident dignissimos nam eligendi consequuntur hic. Deserunt, itaque? Quos culpa fuga voluptatem nostrum nam consectetur non, repellendus hic voluptatibus harum cupiditate maiores fugit dolorum, quis tempora laboriosam excepturi optio reprehenderit labore neque odit maxime. Quaerat, iure, possimus blanditiis modi tempore alias nobis, corporis nemo voluptates deleniti quasi tempora quis amet ullam temporibus repudiandae vitae dolorum quae sit. Saepe architecto accusamus error temporibus amet consectetur, accusantium fugit voluptatem non culpa distinctio magnam tempore rem porro incidunt aut alias magni officiis voluptates vero optio aspernatur quis neque. Repellendus unde soluta porro ut illo laboriosam delectus, odit error, totam debitis cum libero quis quasi culpa quam id. Dolore dolorem nam repellat, illum cum architecto omnis, magnam autem provident rerum fuga eaque itaque, ipsum odio adipisci dolores incidunt totam. Temporibus nostrum amet odio natus veniam possimus aut mollitia id a, voluptas, aliquid ullam, qui corrupti quaerat ipsum illo earum ratione maiores. Temporibus impedit omnis fugiat quod perferendis, eveniet, nihil eligendi blanditiis rerum id unde soluta consequatur labore harum eaque atque iure ea quam.
      deleniti! Exercitationem esse fugiat dolore molestiae eos.
   </p> </div>
   </div>
}